
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: snoopy-operator-role
rules:
- apiGroups:
  - pcap.fennecproject.io
  resources:
  - tcpdumps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pcap.fennecproject.io
  resources:
  - tcpdumps/finalizers
  verbs:
  - update
- apiGroups:
  - pcap.fennecproject.io
  resources:
  - tcpdumps/status
  verbs:
  - get
  - patch
  - update
