
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pcap.snoopy-operator.io
  resources:
  - tcpdumps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pcap.snoopy-operator.io
  resources:
  - tcpdumps/finalizers
  verbs:
  - update
- apiGroups:
  - pcap.snoopy-operator.io
  resources:
  - tcpdumps/status
  verbs:
  - get
  - patch
  - update
