# permissions for end users to edit snoopyjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snoopyjob-editor-role
rules:
- apiGroups:
  - job.fennecproject.io
  resources:
  - snoopyjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - job.fennecproject.io
  resources:
  - snoopyjobs/status
  verbs:
  - get
