# permissions for end users to view snoopyjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: snoopyjob-viewer-role
rules:
- apiGroups:
  - job.fennecproject.io
  resources:
  - snoopyjobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - job.fennecproject.io
  resources:
  - snoopyjobs/status
  verbs:
  - get
