apiVersion: exec.fennecproject.io/v1alpha1
kind: Command
metadata:
  name: command-sample
spec:
  command: "tcpdump"
  args: "-i eth0 -c 10"
  labelSelector: { 
    networkMonitor: "true",
    }
  targetNamespace: cnf-telco

