apiVersion: v1
kind: Namespace
metadata:
  name: cnf-telco
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cnf-telco-sa
  namespace: cnf-telco
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnf-iperf-server-pod
  namespace: cnf-telco
  labels:
    networkMonitor: "true"
spec:
  selector:
    matchLabels:
      networkMonitor: "true"
  replicas: 1
  template:
    metadata:
      name: cnf-iperf-server-pod
      namespace: cnf-telco
      labels:
        networkMonitor: "true"
    spec:
      serviceAccountName: cnf-telco-sa
      containers:
      - command:
        - /bin/bash
        - -c
        - --
        args:
        - "iperf -s"
        image: "nicolaka/netshoot:latest"
        imagePullPolicy: Always
        name: cnf-iperf-server
---
apiVersion: v1
kind: Service
metadata:
    name: iperf-server-svc
    namespace: cnf-telco
spec:
  ports:
  - name: iperf-server-svc
    port: 5001
    protocol: TCP
    targetPort: 5001
  selector:
    networkMonitor: "true"
  type: ClusterIP
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cnf-iperf-client
  namespace: cnf-telco
spec:
  template:
    spec:
      containers:
      - name: cnf-iperf-client
        image: "nicolaka/netshoot:latest"
        command: ["/bin/bash",  "-c", "iperf -c iperf-server-svc.cnf-telco.svc.cluster.local", "-f K -w 500K -P 2 -t 300s -i 1s"]
      restartPolicy: Never
  backoffLimit: 4